### PR TITLE
Updated for NetLogo 6.0

### PR DESCRIPTION
**Pull request by cstaelin**
Here's the Shell Extension update for v6.0.  Aside from the java file, I updated the Makefile to handle the way the Netlogo jar file is now named and the README file to elaborate a bit on what the extension does and does not do.  My handling of the makefile is a bit idiosyncratic, so you may want to take a close look at that.
I will shortly upload a test model that you may or may not want to include.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
What I see so far looks good. I'll wait for you to add the test model before merging, unless you would prefer I go ahead with the merge. Thanks again!

**Comment by cstaelin** [comment]
uploaded it, but forgot to issue a new pull request. you should have it now.

**Comment by cstaelin** [comment]
Robert,

It's now there.  BTW, any word on the new BS issue I posted?

Best,
Charles


-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063

**Comment by mrerrormessage** [comment]
Thanks again! I'll update the BS issue shortly.

**Pull request merged**
